# Generated by Django 4.1.3 on 2022-11-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hoteluser_address'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hoteluser'),
        ),
        migrations.CreateModel(
            name='RoomPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('UNVERIFIED', 'UNVERIFIED'), ('VERIFIED', 'VERIFIED')], default='WAITING', max_length=30)),
                ('room_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomorder')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField()),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkout_set', to='accounts.hoteluser')),
                ('room_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomorder')),
                ('verificator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificator_checkout_set', to='accounts.hoteluser')),
            ],
        ),
    ]
