# Generated by Django 4.1.3 on 2022-12-08 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(
                2022, 12, 8, 13, 12, 44, 858106)),
        ),
    ]
