# Generated by Django 4.1.3 on 2022-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='role',
            field=models.CharField(choices=[('HOTEL_ADMINISTRATOR', 'HOTEL_ADMINISTRATOR'), ('HOTEL_SUPERVISOR', 'HOTEL_SUPERVISOR'), ('GUEST', 'GUEST')], max_length=30),
        ),
    ]
