# Generated by Django 4.1.3 on 2022-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hoteluser_guest_status_hoteluser_works_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
