# Generated by Django 4.1.3 on 2022-11-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_facility'),
        ('accounts', '0005_hoteluser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='guest_current_stay',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_stay', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='hoteluser',
            name='works_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_work', to='hotel.hotel'),
        ),
    ]
