# Generated by Django 4.1.3 on 2022-12-08 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_facility'),
        ('accounts', '0006_hoteluser_guest_current_stay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='guest_current_stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_stay', to='hotel.hotel'),
        ),
    ]
