# Generated by Django 4.1.3 on 2022-11-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE')], default='AVAILABLE', max_length=30),
        ),
        migrations.CreateModel(
            name='RoomServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('UNVERIFIED', 'UNVERIFIED'), ('VERIFIED', 'VERIFIED')], default='WAITING', max_length=30)),
                ('room_service_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roomservice.roomserviceorder')),
            ],
        ),
    ]
