# Generated by Django 4.1.3 on 2022-11-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_facility'),
        ('accounts', '0005_hoteluser_address'),
        ('roomservice', '0002_roomservice_status_roomservicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservice',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_services', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='roomserviceorder',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_services_orders', to='accounts.hoteluser'),
        ),
        migrations.AlterField(
            model_name='roomserviceorder',
            name='room_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_services_orders', to='roomservice.roomservice'),
        ),
    ]
