# Generated by Django 4.1.3 on 2022-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomservice', '0003_alter_roomservice_hotel_alter_roomserviceorder_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservicepayment',
            name='price',
        ),
        migrations.AddField(
            model_name='roomservice',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='roomserviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('PROCESSED', 'PROCESSED'), ('REJECTED', 'REJECTED'), ('FINISHED', 'FINISHED')], default='AVAILABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='roomservicepayment',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
