# Generated by Django 4.1.3 on 2022-12-01 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomservice', '0004_remove_roomservicepayment_price_roomservice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomserviceorder',
            name='notes',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='roomserviceorder',
            name='time_served',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='roomserviceorder',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('PROCESSED', 'PROCESSED'), ('REJECTED', 'REJECTED'), ('FINISHED', 'FINISHED')], default='WAITING', max_length=30),
        ),
    ]
