# Generated by Django 4.1.3 on 2022-12-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomservice', '0005_roomserviceorder_notes_roomserviceorder_time_served_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='img_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='roomservice',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
