# Generated by Django 4.1.3 on 2022-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomservice', '0008_roomserviceorder_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservicepayment',
            old_name='amount',
            new_name='total_price',
        ),
    ]
